#!/bin/sh

set -ex

[ ! -d ./lib/node_modules ] && cd ./lib && npm install && cd ../
[ ! -d ./electron/node_modules ] && cd ./electron && npm install && cd ../
[ ! -L ./electron/node_modules/TabooLib ] && ln -s ../../lib ./electron/node_modules/TabooLib
[ ! -d ./electron/src/TabooUI ] && cp -r ./webui/src ./electron/src/TabooUI
[ ! -d ./electron/public ] && cp -r ./webui/src ./electron/public

cd electron
npm run build
npm run start
